#!/bin/bash

#get admin priviledges
sudo su

#install apache and insert html
yum update -y
yum install -y httpd.x86_64
systemctl start httpd.service
systemctl enable httpd.service
echo "Hello World from $(hostname -f)" > /var/www/html/index.html


#install docker
$yum update -y
$yum install -y docker

$service docker start
$usermod -a -G docker ec2-user

#get jar and dockerfile from s3
$cd /var/www
$wget https://frontdesk-test.s3.ap-south-1.amazonaws.com/frontDesk-1.0.0.1.jar
$wget https://frontdesk-test.s3.ap-south-1.amazonaws.com/Dockerfile
